--- 
title: "Cenozoic Caribbean Corals"
author: "Lewis A. Jones"
format: 
  dashboard:
    orientation: rows
    theme: yeti
---

```{r}
library(leaflet)
library(sf)
library(reactable)
pbdb <- read.csv("./data/data/pbdb.csv")
pbdb <- pbdb[1:10, ]
pbdb$content <- paste(sep = "<br/>",
                      "Collection number:",
                      pbdb$collection_no,
                      "lng = ", pbdb$lng,
                      "lat = ", pbdb$lat
                      )
```
```{r stats}
ccc_stats <- data.frame(collections = length(unique(pbdb$collection_no)),
                        occurrences = length(unique(pbdb$occurrence_no)),
                        taxa = length(unique(pbdb$accepted_name)))
```

```{r map}
ccc_map <- pbdb |> 
  leaflet() |> 
  addProviderTiles(providers$CartoDB.Positron) |> 
  setView(lng = -77, lat = 18, zoom = 4) |> 
  addCircleMarkers(data = pbdb,
                   lng = ~lng,
                   lat = ~lat,
                   layerId = ~collection_no,
                   popup = ~content,
                   radius = 5,
                   stroke = TRUE,
                   weight = 1,
                   opacity = 1,
                   color = "#36454F",
                   fillColor = ~col,
                   fillOpacity = 0.5)
```

```{r table}
ccc_table <- pbdb |> 
  reactable(searchable = TRUE,
            theme = reactableTheme(
              style = list(fontSize = "0.75em")))
```

# Home

# Data

## Row

### Column {width=25%}

#### Row

```{r}
#| component: valuebox
#| title: Number of sampling events
list(
  icon = "search",
  color = "purple",
  value = as.numeric(ccc_stats$collections)
)
```

#### Row

```{r}
#| component: valuebox
#| title: Number of occurrences
list(
  icon = "map",
  color = "blue",
  value = as.numeric(ccc_stats$occurrences)
)
```

#### Row

```{r}
#| component: valuebox
#| title: Number of taxa 
list(
  icon = "card-checklist",
  color = "green",
  value = as.numeric(ccc_stats$taxa)
)
```

### Column

```{r}
#| title: Map
ccc_map
```

## Row

```{r}
#| title: Table
ccc_table
```

# Diversity

# Morphology

# Glossary

# References

# Download